### ISSUE TITLE
Feature request: Chat history

### ISSUE THREAD

**Issue by JacekJagosz** [communi/communi-sailfish#142] opened 2019-09-12 06:20 UTC
It would be extremely helpful it the app kept messages received before closing of the app. For the purpose of not loosing messages when the app crashed or after restarting the phone, and remembering a conversation from days ago.
Most desktop or Android apps have it, and I really miss it in my favourite IRC app.

**Comment by Thaodan** [comment] 2019-09-23 07:23
Or restore history from ZNC if possible?

**Comment by Thaodan** [comment] 2022-07-19 23:03
Duplicate of #47.

**Closed by Thaodan** 2022-07-19 23:03 UTC
Labels: Duplicate
